export enum API_ACTIONS {
    FIREBASE_SYNC = 'FIREBASE_SYNC',
    FIREBASE_ERROR = 'FIREBASE_ERROR',
    FIREBASE_SUCCESS = 'FIREBASE_SUCCESS',
    FIREBASE_CREATE_NEW_LIST = "FIREBASE_CREATE_NEW_LIST",
    FIREBASE_LIST_ID_CHANGED = "FIREBASE_LIST_ID_CHANGED"
}
