export enum PRODUCT_ACTIONS {
    ADD_PRODUCT = 'ADD_PRODUCT',
    REMOVE_PRODUCT = 'REMOVE_PRODUCT',
    QUANTITY_PLUS = 'QUANTITY_PLUS',
    QUANTITY_MINUS = 'QUANTITY_MINUS',
    BUY = 'BUY',
    EDIT = 'EDIT',
    GET_PRODUCTS_FROM_FIREBASE = "GET_PRODUCTS_FROM_FIREBASE"
}
