export enum PRODUCT_ACTIONS {
    ADD_PRODUCT = 'ADD_PRODUCT',
    REMOVE_PRODUCT = 'REMOVE_PRODUCT',
    QUANTITY_PLUS = 'QUANTITY_PLUS',
    QUANTITY_MINUS = 'QUANTITY_MINUS',
    BUY = 'BUY',
    EDIT = 'PRODUCT_EDIT',
    GET_PRODUCTS_FROM_FIREBASE = 'GET_FROM_FIREBASE_PRODUCTS',
    GET_PRODUCT_FROM_FIREBASE = 'GET_FROM_FIREBASE_PRODUCT',
    REMOVE_PRODUCT_FROM_FIREBASE = 'REMOVE_PRODUCT_FROM_FIREBASE',
    UNBUY_ALL_PRODUCTS = 'UNBUY_ALL_PRODUCTS'
}
